package com.example.demo.entity;
// Generated 5 juin 2023, 20:00:47 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import jakarta.persistence.*;

import static jakarta.persistence.GenerationType.IDENTITY;


/**
 * Administrateur generated by hbm2java
 */
@Entity
@Table(name = "administrateur", catalog = "pfe", uniqueConstraints = @UniqueConstraint(columnNames = "UserName"))
public class Administrateur implements java.io.Serializable {

	private Integer idAd;
	private String nomAdm;
	private String prenomAdm;
	private String email;
	private String userName;
	private String password;
	private Date dateNaissenceAdm;
	private Date dateInscpAdm;
	private String numTele;

	public Administrateur() {
	}

	public Administrateur(String nomAdm, String prenomAdm, String email, String userName, String password,
			Date dateInscpAdm) {
		this.nomAdm = nomAdm;
		this.prenomAdm = prenomAdm;
		this.email = email;
		this.userName = userName;
		this.password = password;
		this.dateInscpAdm = dateInscpAdm;
	}

	public Administrateur(String nomAdm, String prenomAdm, String email, String userName, String password,
			Date dateNaissenceAdm, Date dateInscpAdm, String numTele) {
		this.nomAdm = nomAdm;
		this.prenomAdm = prenomAdm;
		this.email = email;
		this.userName = userName;
		this.password = password;
		this.dateNaissenceAdm = dateNaissenceAdm;
		this.dateInscpAdm = dateInscpAdm;
		this.numTele = numTele;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_ad", unique = true, nullable = false)
	public Integer getIdAd() {
		return this.idAd;
	}

	public void setIdAd(Integer idAd) {
		this.idAd = idAd;
	}

	@Column(name = "nom_adm", nullable = false, length = 45)
	public String getNomAdm() {
		return this.nomAdm;
	}

	public void setNomAdm(String nomAdm) {
		this.nomAdm = nomAdm;
	}

	@Column(name = "prenom_adm", nullable = false, length = 45)
	public String getPrenomAdm() {
		return this.prenomAdm;
	}

	public void setPrenomAdm(String prenomAdm) {
		this.prenomAdm = prenomAdm;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "UserName", unique = true, nullable = false, length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_naissence_adm", length = 10)
	public Date getDateNaissenceAdm() {
		return this.dateNaissenceAdm;
	}

	public void setDateNaissenceAdm(Date dateNaissenceAdm) {
		this.dateNaissenceAdm = dateNaissenceAdm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_inscp_adm", nullable = false, length = 10)
	public Date getDateInscpAdm() {
		return this.dateInscpAdm;
	}

	public void setDateInscpAdm(Date dateInscpAdm) {
		this.dateInscpAdm = dateInscpAdm;
	}

	@Column(name = "num_tele")
	public String getNumTele() {
		return this.numTele;
	}

	public void setNumTele(String numTele) {
		this.numTele = numTele;
	}

}
