package com.example.demo.entity;
// Generated 31 mai 2023, 18:41:19 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import jakarta.persistence.*;
/**
 * Administrateur generated by hbm2java
 */
@Entity
@Table(name = "administrateur", catalog = "pfe", uniqueConstraints = @UniqueConstraint(columnNames = "UserName"))
public class Administrateur implements java.io.Serializable {

	private int idAd;
	private Message message;
	private String nomAdm;
	private String prenomAdm;
	private String email;
	private String userName;
	private String password;
	private Date dateNaissenceAdm;
	private Date dateInscpAdm;
	private int numTele;

	public Administrateur() {
	}

	public Administrateur(int idAd, Message message, String nomAdm, String prenomAdm, String email, String userName,
			String password, Date dateNaissenceAdm, Date dateInscpAdm, int numTele) {
		this.idAd = idAd;
		this.message = message;
		this.nomAdm = nomAdm;
		this.prenomAdm = prenomAdm;
		this.email = email;
		this.userName = userName;
		this.password = password;
		this.dateNaissenceAdm = dateNaissenceAdm;
		this.dateInscpAdm = dateInscpAdm;
		this.numTele = numTele;
	}

	@Id

	@Column(name = "id_ad", unique = true, nullable = false)
	public int getIdAd() {
		return this.idAd;
	}

	public void setIdAd(int idAd) {
		this.idAd = idAd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "message", nullable = false)
	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	@Column(name = "nom_adm", nullable = false, length = 45)
	public String getNomAdm() {
		return this.nomAdm;
	}

	public void setNomAdm(String nomAdm) {
		this.nomAdm = nomAdm;
	}

	@Column(name = "prenom_adm", nullable = false, length = 45)
	public String getPrenomAdm() {
		return this.prenomAdm;
	}

	public void setPrenomAdm(String prenomAdm) {
		this.prenomAdm = prenomAdm;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "UserName", unique = true, nullable = false, length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_naissence_adm", nullable = false, length = 10)
	public Date getDateNaissenceAdm() {
		return this.dateNaissenceAdm;
	}

	public void setDateNaissenceAdm(Date dateNaissenceAdm) {
		this.dateNaissenceAdm = dateNaissenceAdm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_inscp_adm", nullable = false, length = 10)
	public Date getDateInscpAdm() {
		return this.dateInscpAdm;
	}

	public void setDateInscpAdm(Date dateInscpAdm) {
		this.dateInscpAdm = dateInscpAdm;
	}

	@Column(name = "num_tele", nullable = false)
	public int getNumTele() {
		return this.numTele;
	}

	public void setNumTele(int numTele) {
		this.numTele = numTele;
	}

}
