package com.example.demo.entity;
// Generated 31 mai 2023, 18:41:19 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import jakarta.persistence.*;

/**
 * Chapitre generated by hbm2java
 */
@Entity
@Table(name = "chapitre", catalog = "pfe")
public class Chapitre implements java.io.Serializable {

	private int idChpt;
	private Modul module;
	private String titre;
	private Date dateAjoute;

	public Chapitre() {
	}

	public Chapitre(int idChpt, Modul module, String titre, Date dateAjoute) {
		this.idChpt = idChpt;
		this.module = module;
		this.titre = titre;
		this.dateAjoute = dateAjoute;
	}

	@Id

	@Column(name = "id_chpt", unique = true, nullable = false)
	public int getIdChpt() {
		return this.idChpt;
	}

	public void setIdChpt(int idChpt) {
		this.idChpt = idChpt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module", nullable = false)
	public Modul getModule() {
		return this.module;
	}

	public void setModule(Modul module) {
		this.module = module;
	}

	@Column(name = "titre", nullable = false, length = 45)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_ajoute", nullable = false, length = 10)
	public Date getDateAjoute() {
		return this.dateAjoute;
	}

	public void setDateAjoute(Date dateAjoute) {
		this.dateAjoute = dateAjoute;
	}

}
