package com.example.demo.entity;
// Generated 31 mai 2023, 18:41:19 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Departement generated by hbm2java
 */
@Entity
@Table(name = "departement", catalog = "pfe")
public class Departement implements java.io.Serializable {

	private int idDep;
	private String nomDep;
	private Set<Filiere> filieres = new HashSet<Filiere>(0);

	public Departement() {
	}

	public Departement(int idDep, String nomDep) {
		this.idDep = idDep;
		this.nomDep = nomDep;
	}

	public Departement(int idDep, String nomDep, Set<Filiere> filieres) {
		this.idDep = idDep;
		this.nomDep = nomDep;
		this.filieres = filieres;
	}

	@Id

	@Column(name = "id_dep", unique = true, nullable = false)
	public int getIdDep() {
		return this.idDep;
	}

	public void setIdDep(int idDep) {
		this.idDep = idDep;
	}

	@Column(name = "nom_dep", nullable = false, length = 45)
	public String getNomDep() {
		return this.nomDep;
	}

	public void setNomDep(String nomDep) {
		this.nomDep = nomDep;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departement")
	public Set<Filiere> getFilieres() {
		return this.filieres;
	}

	public void setFilieres(Set<Filiere> filieres) {
		this.filieres = filieres;
	}

}
