package com.example.demo.entity;
// Generated 5 juin 2023, 20:00:47 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * Departement generated by hbm2java
 */
@Entity
@Table(name = "departement", catalog = "pfe")
public class Departement implements java.io.Serializable {

	private Integer idDep;
	private String nomDep;
	private Set<Filiere> filieres = new HashSet<Filiere>(0);

	public Departement() {
	}

	public Departement(String nomDep) {
		this.nomDep = nomDep;
	}

	public Departement(String nomDep, Set<Filiere> filieres) {
		this.nomDep = nomDep;
		this.filieres = filieres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_dep", unique = true, nullable = false)
	public Integer getIdDep() {
		return this.idDep;
	}

	public void setIdDep(Integer idDep) {
		this.idDep = idDep;
	}

	@Column(name = "nom_dep", nullable = false, length = 45)
	public String getNomDep() {
		return this.nomDep;
	}

	public void setNomDep(String nomDep) {
		this.nomDep = nomDep;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departement")
	public Set<Filiere> getFilieres() {
		return this.filieres;
	}

	public void setFilieres(Set<Filiere> filieres) {
		this.filieres = filieres;
	}

}
