package com.example.demo.entity;
// Generated 5 juin 2023, 20:00:47 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;
import org.springframework.format.annotation.DateTimeFormat;

import static jakarta.persistence.GenerationType.IDENTITY;


/**
 * Enseignant generated by hbm2java
 */
@Entity
@Table(name = "enseignant", catalog = "pfe", uniqueConstraints = @UniqueConstraint(columnNames = "User_Name"))
public class Enseignant implements java.io.Serializable {

	private Integer idEng;
	private String nomEng;
	private String prenomEng;
	private String email;
	private String userName;
	private String password;
	private Date dateNaissanceEng;
	private Date dateInscpEng;
	private String numTele;
	private Set<Modul> moduls = new HashSet<Modul>(0);

	public Enseignant() {
	}

	public Enseignant(String nomEng, String prenomEng, String email, String userName, String password,
			Date dateInscpEng) {
		this.nomEng = nomEng;
		this.prenomEng = prenomEng;
		this.email = email;
		this.userName = userName;
		this.password = password;
		this.dateInscpEng = dateInscpEng;
	}

	public Enseignant(String nomEng, String prenomEng, String email, String userName, String password,
			Date dateNaissanceEng, Date dateInscpEng, String numTele, Set<Modul> moduls) {
		this.nomEng = nomEng;
		this.prenomEng = prenomEng;
		this.email = email;
		this.userName = userName;
		this.password = password;
		this.dateNaissanceEng = dateNaissanceEng;
		this.dateInscpEng = dateInscpEng;
		this.numTele = numTele;
		this.moduls = moduls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_eng", unique = true, nullable = false)
	public Integer getIdEng() {
		return this.idEng;
	}

	public void setIdEng(Integer idEng) {
		this.idEng = idEng;
	}

	@Column(name = "nom_eng", nullable = false, length = 45)
	public String getNomEng() {
		return this.nomEng;
	}

	public void setNomEng(String nomEng) {
		this.nomEng = nomEng;
	}

	@Column(name = "prenom_eng", nullable = false, length = 45)
	public String getPrenomEng() {
		return this.prenomEng;
	}

	public void setPrenomEng(String prenomEng) {
		this.prenomEng = prenomEng;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "User_Name", unique = true, nullable = false, length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@Column(name = "Date_naissance_eng", length = 10)
	public Date getDateNaissanceEng() {
		return this.dateNaissanceEng;
	}

	public void setDateNaissanceEng(Date dateNaissanceEng) {
		this.dateNaissanceEng = dateNaissanceEng;
	}

	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@Column(name = "Date_inscp_eng", columnDefinition = "DATE DEFAULT CURRENT_DATE", nullable = true, length = 10)
	public Date getDateInscpEng() {
		return this.dateInscpEng;
	}

	public void setDateInscpEng(Date dateInscpEng) {
		this.dateInscpEng = dateInscpEng;
	}

	@Column(name = "num_tele")
	public String getNumTele() {
		return this.numTele;
	}

	public void setNumTele(String numTele) {
		this.numTele = numTele;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "enseignant")
	public Set<Modul> getModuls() {
		return this.moduls;
	}

	public void setModuls(Set<Modul> moduls) {
		this.moduls = moduls;
	}

}
