package com.example.demo.entity;
// Generated 31 mai 2023, 18:41:19 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import jakarta.persistence.*;

/**
 * Enseignant generated by hbm2java
 */
@Entity
@Table(name = "enseignant", catalog = "pfe", uniqueConstraints = @UniqueConstraint(columnNames = "User_Name"))
public class Enseignant implements java.io.Serializable {

	private int idEng;
	private Message message;
	private Modul module;
	private String nomEng;
	private String prenomEng;
	private String email;
	private String userName;
	private String password;
	private Date dateNaissanceEng;
	private Date dateInscpEng;
	private int numTele;

	public Enseignant() {
	}

	public Enseignant(int idEng, Message message, Modul module, String nomEng, String prenomEng, String email,
                      String userName, String password, Date dateNaissanceEng, Date dateInscpEng, int numTele) {
		this.idEng = idEng;
		this.message = message;
		this.module = module;
		this.nomEng = nomEng;
		this.prenomEng = prenomEng;
		this.email = email;
		this.userName = userName;
		this.password = password;
		this.dateNaissanceEng = dateNaissanceEng;
		this.dateInscpEng = dateInscpEng;
		this.numTele = numTele;
	}

	@Id

	@Column(name = "id_eng", unique = true, nullable = false)
	public int getIdEng() {
		return this.idEng;
	}

	public void setIdEng(int idEng) {
		this.idEng = idEng;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "message", nullable = false)
	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module", nullable = false)
	public Modul getModule() {
		return this.module;
	}

	public void setModule(Modul module) {
		this.module = module;
	}

	@Column(name = "nom_eng", nullable = false, length = 45)
	public String getNomEng() {
		return this.nomEng;
	}

	public void setNomEng(String nomEng) {
		this.nomEng = nomEng;
	}

	@Column(name = "prenom_eng", nullable = false, length = 45)
	public String getPrenomEng() {
		return this.prenomEng;
	}

	public void setPrenomEng(String prenomEng) {
		this.prenomEng = prenomEng;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "User_Name", unique = true, nullable = false, length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_naissance_eng", nullable = false, length = 10)
	public Date getDateNaissanceEng() {
		return this.dateNaissanceEng;
	}

	public void setDateNaissanceEng(Date dateNaissanceEng) {
		this.dateNaissanceEng = dateNaissanceEng;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_inscp_eng", nullable = false, length = 10)
	public Date getDateInscpEng() {
		return this.dateInscpEng;
	}

	public void setDateInscpEng(Date dateInscpEng) {
		this.dateInscpEng = dateInscpEng;
	}

	@Column(name = "num_tele", nullable = false)
	public int getNumTele() {
		return this.numTele;
	}

	public void setNumTele(int numTele) {
		this.numTele = numTele;
	}

}
