package com.example.demo.entity;
// Generated 5 juin 2023, 20:00:47 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;
import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * Etudiante generated by hbm2java
 */
@Entity
@Table(name = "etudiante", catalog = "pfe", uniqueConstraints = @UniqueConstraint(columnNames = "UserName"))
public class Etudiante implements java.io.Serializable {

	private Integer idEtu;
	private int nomEtu;
	private int prenomEtu;
	private String email;
	private String userName;
	private String password;
	private Date dateNaissanceEtd;
	private Date dateInscpEtd;
	private int filier;
	private String numTele;
	private Set<EtudianteModule> etudianteModules = new HashSet<EtudianteModule>(0);
	private Set<NoteQuiz> noteQuizs = new HashSet<NoteQuiz>(0);

	public Etudiante() {
	}

	public Etudiante(int nomEtu, int prenomEtu, String email, String userName, String password, Date dateInscpEtd,
			int filier) {
		this.nomEtu = nomEtu;
		this.prenomEtu = prenomEtu;
		this.email = email;
		this.userName = userName;
		this.password = password;
		this.dateInscpEtd = dateInscpEtd;
		this.filier = filier;
	}

	public Etudiante(int nomEtu, int prenomEtu, String email, String userName, String password, Date dateNaissanceEtd,
			Date dateInscpEtd, int filier, String numTele, Set<EtudianteModule> etudianteModules,
			Set<NoteQuiz> noteQuizs) {
		this.nomEtu = nomEtu;
		this.prenomEtu = prenomEtu;
		this.email = email;
		this.userName = userName;
		this.password = password;
		this.dateNaissanceEtd = dateNaissanceEtd;
		this.dateInscpEtd = dateInscpEtd;
		this.filier = filier;
		this.numTele = numTele;
		this.etudianteModules = etudianteModules;
		this.noteQuizs = noteQuizs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_etu", unique = true, nullable = false)
	public Integer getIdEtu() {
		return this.idEtu;
	}

	public void setIdEtu(Integer idEtu) {
		this.idEtu = idEtu;
	}

	@Column(name = "nom_etu", nullable = false)
	public int getNomEtu() {
		return this.nomEtu;
	}

	public void setNomEtu(int nomEtu) {
		this.nomEtu = nomEtu;
	}

	@Column(name = "prenom_etu", nullable = false)
	public int getPrenomEtu() {
		return this.prenomEtu;
	}

	public void setPrenomEtu(int prenomEtu) {
		this.prenomEtu = prenomEtu;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "UserName", unique = true, nullable = false, length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_naissance_etd", length = 10)
	public Date getDateNaissanceEtd() {
		return this.dateNaissanceEtd;
	}

	public void setDateNaissanceEtd(Date dateNaissanceEtd) {
		this.dateNaissanceEtd = dateNaissanceEtd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_inscp_etd", nullable = false, length = 10)
	public Date getDateInscpEtd() {
		return this.dateInscpEtd;
	}

	public void setDateInscpEtd(Date dateInscpEtd) {
		this.dateInscpEtd = dateInscpEtd;
	}

	@Column(name = "filier", nullable = false)
	public int getFilier() {
		return this.filier;
	}

	public void setFilier(int filier) {
		this.filier = filier;
	}

	@Column(name = "Num_tele")
	public String getNumTele() {
		return this.numTele;
	}

	public void setNumTele(String numTele) {
		this.numTele = numTele;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etudiante")
	public Set<EtudianteModule> getEtudianteModules() {
		return this.etudianteModules;
	}

	public void setEtudianteModules(Set<EtudianteModule> etudianteModules) {
		this.etudianteModules = etudianteModules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etudiante")
	public Set<NoteQuiz> getNoteQuizs() {
		return this.noteQuizs;
	}

	public void setNoteQuizs(Set<NoteQuiz> noteQuizs) {
		this.noteQuizs = noteQuizs;
	}

}
