package com.example.demo.entity;
// Generated 5 juin 2023, 20:00:47 by Hibernate Tools 4.3.5.Final

import jakarta.persistence.*;

import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * EtudianteModule generated by hbm2java
 */
@Entity
@Table(name = "etudiante_module", catalog = "pfe")
public class EtudianteModule implements java.io.Serializable {

	private Integer id;
	private Etudiante etudiante;
	private Modul modul;
	private Integer noteModul;

	public EtudianteModule() {
	}

	public EtudianteModule(Etudiante etudiante, Modul modul) {
		this.etudiante = etudiante;
		this.modul = modul;
	}

	public EtudianteModule(Etudiante etudiante, Modul modul, Integer noteModul) {
		this.etudiante = etudiante;
		this.modul = modul;
		this.noteModul = noteModul;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEtu", nullable = false)
	public Etudiante getEtudiante() {
		return this.etudiante;
	}

	public void setEtudiante(Etudiante etudiante) {
		this.etudiante = etudiante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idModul", nullable = false)
	public Modul getModul() {
		return this.modul;
	}

	public void setModul(Modul modul) {
		this.modul = modul;
	}

	@Column(name = "note_modul")
	public Integer getNoteModul() {
		return this.noteModul;
	}

	public void setNoteModul(Integer noteModul) {
		this.noteModul = noteModul;
	}

}
