package com.example.demo.entity;
// Generated 31 mai 2023, 18:41:19 by Hibernate Tools 4.3.5.Final

import jakarta.persistence.*;

/**
 * Etudiante generated by hbm2java
 */
@Entity
@Table(name = "etudiante", catalog = "pfe", uniqueConstraints = @UniqueConstraint(columnNames = "UserName"))
public class Etudiante implements java.io.Serializable {

	private EtudianteId id;
	private Filiere filiere;
	private Message message;
	private Modul module;

	public Etudiante() {
	}

	public Etudiante(EtudianteId id, Filiere filiere, Message message, Modul module) {
		this.id = id;
		this.filiere = filiere;
		this.message = message;
		this.module = module;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idEtu", column = @Column(name = "id_etu", nullable = false)),
			@AttributeOverride(name = "nomEtu", column = @Column(name = "nom_etu", nullable = false)),
			@AttributeOverride(name = "prenomEtu", column = @Column(name = "prenom_etu", nullable = false)),
			@AttributeOverride(name = "email", column = @Column(name = "email", nullable = false, length = 100)),
			@AttributeOverride(name = "userName", column = @Column(name = "UserName", unique = true, nullable = false, length = 100)),
			@AttributeOverride(name = "password", column = @Column(name = "password", nullable = false, length = 45)),
			@AttributeOverride(name = "dateNaissanceEtd", column = @Column(name = "Date_naissance_etd", nullable = false, length = 10)),
			@AttributeOverride(name = "dateInscpEtd", column = @Column(name = "Date_inscp_etd", nullable = false, length = 10)),
			@AttributeOverride(name = "filier", column = @Column(name = "filier", nullable = false)),
			@AttributeOverride(name = "numTele", column = @Column(name = "Num_tele", nullable = false)),
			@AttributeOverride(name = "note", column = @Column(name = "Note", nullable = false, precision = 12, scale = 0)),
			@AttributeOverride(name = "module", column = @Column(name = "module", nullable = false)),
			@AttributeOverride(name = "message", column = @Column(name = "message", nullable = false)) })
	public EtudianteId getId() {
		return this.id;
	}

	public void setId(EtudianteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "filier", nullable = false, insertable = false, updatable = false)
	public Filiere getFiliere() {
		return this.filiere;
	}

	public void setFiliere(Filiere filiere) {
		this.filiere = filiere;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "message", nullable = false, insertable = false, updatable = false)
	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module", nullable = false, insertable = false, updatable = false)
	public Modul getModule() {
		return this.module;
	}

	public void setModule(Modul module) {
		this.module = module;
	}

}
