package com.example.demo.entity;
// Generated 31 mai 2023, 18:41:19 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import jakarta.persistence.*;

/**
 * EtudianteId generated by hbm2java
 */
@Embeddable
public class EtudianteId implements java.io.Serializable {

	private int idEtu;
	private int nomEtu;
	private int prenomEtu;
	private String email;
	private String userName;
	private String password;
	private Date dateNaissanceEtd;
	private Date dateInscpEtd;
	private int filier;
	private int numTele;
	private float note;
	private int module;
	private int message;

	public EtudianteId() {
	}

	public EtudianteId(int idEtu, int nomEtu, int prenomEtu, String email, String userName, String password,
			Date dateNaissanceEtd, Date dateInscpEtd, int filier, int numTele, float note, int module, int message) {
		this.idEtu = idEtu;
		this.nomEtu = nomEtu;
		this.prenomEtu = prenomEtu;
		this.email = email;
		this.userName = userName;
		this.password = password;
		this.dateNaissanceEtd = dateNaissanceEtd;
		this.dateInscpEtd = dateInscpEtd;
		this.filier = filier;
		this.numTele = numTele;
		this.note = note;
		this.module = module;
		this.message = message;
	}

	@Column(name = "id_etu", nullable = false)
	public int getIdEtu() {
		return this.idEtu;
	}

	public void setIdEtu(int idEtu) {
		this.idEtu = idEtu;
	}

	@Column(name = "nom_etu", nullable = false)
	public int getNomEtu() {
		return this.nomEtu;
	}

	public void setNomEtu(int nomEtu) {
		this.nomEtu = nomEtu;
	}

	@Column(name = "prenom_etu", nullable = false)
	public int getPrenomEtu() {
		return this.prenomEtu;
	}

	public void setPrenomEtu(int prenomEtu) {
		this.prenomEtu = prenomEtu;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "UserName", unique = true, nullable = false, length = 100)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Date_naissance_etd", nullable = false, length = 10)
	public Date getDateNaissanceEtd() {
		return this.dateNaissanceEtd;
	}

	public void setDateNaissanceEtd(Date dateNaissanceEtd) {
		this.dateNaissanceEtd = dateNaissanceEtd;
	}

	@Column(name = "Date_inscp_etd", nullable = false, length = 10)
	public Date getDateInscpEtd() {
		return this.dateInscpEtd;
	}

	public void setDateInscpEtd(Date dateInscpEtd) {
		this.dateInscpEtd = dateInscpEtd;
	}

	@Column(name = "filier", nullable = false)
	public int getFilier() {
		return this.filier;
	}

	public void setFilier(int filier) {
		this.filier = filier;
	}

	@Column(name = "Num_tele", nullable = false)
	public int getNumTele() {
		return this.numTele;
	}

	public void setNumTele(int numTele) {
		this.numTele = numTele;
	}

	@Column(name = "Note", nullable = false, precision = 12, scale = 0)
	public float getNote() {
		return this.note;
	}

	public void setNote(float note) {
		this.note = note;
	}

	@Column(name = "module", nullable = false)
	public int getModule() {
		return this.module;
	}

	public void setModule(int module) {
		this.module = module;
	}

	@Column(name = "message", nullable = false)
	public int getMessage() {
		return this.message;
	}

	public void setMessage(int message) {
		this.message = message;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EtudianteId))
			return false;
		EtudianteId castOther = (EtudianteId) other;

		return (this.getIdEtu() == castOther.getIdEtu()) && (this.getNomEtu() == castOther.getNomEtu())
				&& (this.getPrenomEtu() == castOther.getPrenomEtu())
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getPassword() == castOther.getPassword()) || (this.getPassword() != null
						&& castOther.getPassword() != null && this.getPassword().equals(castOther.getPassword())))
				&& ((this.getDateNaissanceEtd() == castOther.getDateNaissanceEtd())
						|| (this.getDateNaissanceEtd() != null && castOther.getDateNaissanceEtd() != null
								&& this.getDateNaissanceEtd().equals(castOther.getDateNaissanceEtd())))
				&& ((this.getDateInscpEtd() == castOther.getDateInscpEtd())
						|| (this.getDateInscpEtd() != null && castOther.getDateInscpEtd() != null
								&& this.getDateInscpEtd().equals(castOther.getDateInscpEtd())))
				&& (this.getFilier() == castOther.getFilier()) && (this.getNumTele() == castOther.getNumTele())
				&& (this.getNote() == castOther.getNote()) && (this.getModule() == castOther.getModule())
				&& (this.getMessage() == castOther.getMessage());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEtu();
		result = 37 * result + this.getNomEtu();
		result = 37 * result + this.getPrenomEtu();
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getPassword() == null ? 0 : this.getPassword().hashCode());
		result = 37 * result + (getDateNaissanceEtd() == null ? 0 : this.getDateNaissanceEtd().hashCode());
		result = 37 * result + (getDateInscpEtd() == null ? 0 : this.getDateInscpEtd().hashCode());
		result = 37 * result + this.getFilier();
		result = 37 * result + this.getNumTele();
		result = 37 * result + (int) this.getNote();
		result = 37 * result + this.getModule();
		result = 37 * result + this.getMessage();
		return result;
	}

}
