package com.example.demo.entity;
// Generated 5 juin 2023, 20:00:47 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;
import org.springframework.format.annotation.DateTimeFormat;

import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * Exercice generated by hbm2java
 */
@Entity
@Table(name = "exercice", catalog = "pfe")
public class Exercice implements java.io.Serializable {

	private Integer idEx;
	private Modul modul;
	private String nomEx;
	private Date dateAjoute;
	private String Contenue;

	private String Image;

	public Exercice() {
	}

	public Exercice(Modul modul, String nomEx, Date dateAjoute,	String Contenue,String Image) {
		this.modul = modul;
		this.nomEx = nomEx;
		this.dateAjoute = dateAjoute;
		this.Contenue = Contenue;
		this.Image = Image;


	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_ex", unique = true, nullable = false)
	public Integer getIdEx() {
		return this.idEx;
	}

	public void setIdEx(Integer idEx) {
		this.idEx = idEx;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module", nullable = false)
	public Modul getModul() {
		return this.modul;
	}

	public void setModul(Modul modul) {
		this.modul = modul;
	}

	@Column(name = "nom_ex", nullable = false, length = 45)
	public String getNomEx() {
		return this.nomEx;
	}

	public void setNomEx(String nomEx) {
		this.nomEx = nomEx;
	}

	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	@Column(name = "Date_ajoute", nullable = true, columnDefinition = "DATE DEFAULT CURRENT_DATE", length = 10)
	public Date getDateAjoute() {
		return this.dateAjoute;
	}

	public void setDateAjoute(Date dateAjoute) {
		this.dateAjoute = dateAjoute;
	}

	/* Contenu*/
	@Column(name = "Contenue", nullable = false, length = 2250)
	public String getContenue() {
		return this.Contenue;
	}
	public void setContenue(String Contenue) {
		this.Contenue = Contenue;
	}
	/* Contenu*/

	@Column(name = "Image", nullable = true, length = 2250)
	public String getImage() {
		return this.Image;
	}
	public void setImage(String Image) {
		this.Image = Image;
	}
}
