package com.example.demo.entity;
// Generated 31 mai 2023, 18:41:19 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Filiere generated by hbm2java
 */
@Entity
@Table(name = "filiere", catalog = "pfe")
public class Filiere implements java.io.Serializable {

	private int idFil;
	private Departement departement;
	private String nomFil;
	private String codeFil;
	private Set<Etudiante> etudiantes = new HashSet<Etudiante>(0);
	private Set<Modul> moduls = new HashSet<Modul>();



	public Filiere() {
	}

	public Filiere(int idFil, Departement departement, String nomFil, String codeFil) {
		this.idFil = idFil;
		this.departement = departement;
		this.nomFil = nomFil;
		this.codeFil = codeFil;
	}

	public Filiere(int idFil, Departement departement, String nomFil, String codeFil,
			Set<Etudiante> etudiantes) {
		this.idFil = idFil;
		this.departement = departement;
		this.nomFil = nomFil;
		this.codeFil = codeFil;
		this.etudiantes = etudiantes;
	}

	@Id

	@Column(name = "id_fil", unique = true, nullable = false)
	public int getIdFil() {
		return this.idFil;
	}

	public void setIdFil(int idFil) {
		this.idFil = idFil;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Departement", nullable = false)
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	@Column(name = "Nom_fil", nullable = false, length = 45)
	public String getNomFil() {
		return this.nomFil;
	}

	public void setNomFil(String nomFil) {
		this.nomFil = nomFil;
	}

	@Column(name = "Code_fil", nullable = false, length = 45)
	public String getCodeFil() {
		return this.codeFil;
	}

	public void setCodeFil(String codeFil) {
		this.codeFil = codeFil;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filiere")
	public Set<Etudiante> getEtudiantes() {
		return this.etudiantes;
	}

	public void setEtudiantes(Set<Etudiante> etudiantes) {
		this.etudiantes = etudiantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filier")
	public Set<Modul> getModuls() {
		return moduls;
	}

	public void setModuls(Set<Modul> moduls) {
		this.moduls = moduls;
	}

	@Override
	public String toString() {
		return "Filiere{" +
				"idFil=" + idFil +
				", departement=" + departement +
				", nomFil='" + nomFil + '\'' +
				", codeFil='" + codeFil + '\'' +
				", etudiantes=" + etudiantes +
				", moduls=" + moduls +
				'}';
	}
}
