package com.example.demo.entity;
// Generated 5 juin 2023, 20:00:47 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;
import static jakarta.persistence.GenerationType.IDENTITY;


/**
 * Filiere generated by hbm2java
 */
@Entity
@Table(name = "filiere", catalog = "pfe")
public class Filiere implements java.io.Serializable {

	private Integer idFil;
	private Departement departement;
	private String nomFil;
	private String codeFil;
	private Set<Modul> moduls = new HashSet<Modul>(0);

	public Filiere() {
	}

	public Filiere(Departement departement, String nomFil, String codeFil) {
		this.departement = departement;
		this.nomFil = nomFil;
		this.codeFil = codeFil;
	}

	public Filiere(Departement departement, String nomFil, String codeFil, Set<Modul> moduls) {
		this.departement = departement;
		this.nomFil = nomFil;
		this.codeFil = codeFil;
		this.moduls = moduls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_fil", unique = true, nullable = false)
	public Integer getIdFil() {
		return this.idFil;
	}

	public void setIdFil(Integer idFil) {
		this.idFil = idFil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Departement", nullable = false)
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	@Column(name = "Nom_fil", nullable = false, length = 45)
	public String getNomFil() {
		return this.nomFil;
	}

	public void setNomFil(String nomFil) {
		this.nomFil = nomFil;
	}

	@Column(name = "Code_fil", nullable = false, length = 45)
	public String getCodeFil() {
		return this.codeFil;
	}

	public void setCodeFil(String codeFil) {
		this.codeFil = codeFil;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filiere")
	public Set<Modul> getModuls() {
		return this.moduls;
	}

	public void setModuls(Set<Modul> moduls) {
		this.moduls = moduls;
	}

}
