package com.example.demo.entity;
// Generated 31 mai 2023, 18:41:19 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "module", catalog = "pfe")
public class Modul implements java.io.Serializable {

	private int idModul;
	private String nomModul;
	private Filiere filier;
	private String enseignante;
	private Set<Exercice> exercices = new HashSet<Exercice>(0);
	private Set<Chapitre> chapitres = new HashSet<Chapitre>(0);
	private Set<Etudiante> etudiantes = new HashSet<Etudiante>(0);
	private Set<Enseignant> enseignants = new HashSet<Enseignant>(0);
	private Set<Quiz> quizs = new HashSet<Quiz>(0);
	public Modul() {
	}

	public Modul(int idModul, String nomModul, Filiere filier, String enseignante) {
		this.idModul = idModul;
		this.nomModul = nomModul;
		this.filier = filier;
		this.enseignante = enseignante;
	}

	public Modul(int idModul, String nomModul, Filiere filier, String enseignante, Set<Exercice> exercices,
			Set<Chapitre> chapitres, Set<Etudiante> etudiantes, Set<Enseignant> enseignants, Set<Quiz> quizs) {
		this.idModul = idModul;
		this.nomModul = nomModul;
		this.filier = filier;
		this.enseignante = enseignante;
		this.exercices = exercices;
		this.chapitres = chapitres;
		this.etudiantes = etudiantes;
		this.enseignants = enseignants;
		this.quizs = quizs;
	}

	@Id

	@Column(name = "id_modul", unique = true, nullable = false)
	public int getIdModul() {
		return this.idModul;
	}

	public void setIdModul(int idModul) {
		this.idModul = idModul;
	}

	@Column(name = "nom_modul", nullable = false, length = 45)
	public String getNomModul() {
		return this.nomModul;
	}

	public void setNomModul(String nomModul) {
		this.nomModul = nomModul;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "filier", nullable = false)
	public Filiere getFilier() {
		return this.filier;
	}
	public void setFilier(Filiere Filiere) {
		this.filier = filier;
	}

	@Column(name = "enseignante", nullable = true, length = 45)
	public String getEnseignante() {
		return this.enseignante;
	}

	public void setEnseignante(String enseignante) {
		this.enseignante = enseignante;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<Exercice> getExercices() {
		return this.exercices;
	}

	public void setExercices(Set<Exercice> exercices) {
		this.exercices = exercices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<Chapitre> getChapitres() {
		return this.chapitres;
	}

	public void setChapitres(Set<Chapitre> chapitres) {
		this.chapitres = chapitres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<Etudiante> getEtudiantes() {
		return this.etudiantes;
	}

	public void setEtudiantes(Set<Etudiante> etudiantes) {
		this.etudiantes = etudiantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<Enseignant> getEnseignants() {
		return this.enseignants;
	}

	public void setEnseignants(Set<Enseignant> enseignants) {
		this.enseignants = enseignants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "module")
	public Set<Quiz> getQuizs() {
		return this.quizs;
	}

	public void setQuizs(Set<Quiz> quizs) {
		this.quizs = quizs;
	}

	@Override
	public String toString() {
		return "Modul{" +
				"idModul=" + idModul +
				", nomModul='" + nomModul + '\'' +
				", filier=" + filier +
				", enseignante='" + enseignante + '\'' +
				", exercices=" + exercices +
				", chapitres=" + chapitres +
				", etudiantes=" + etudiantes +
				", enseignants=" + enseignants +
				", quizs=" + quizs +
				'}';
	}
}
