package com.example.demo.entity;
// Generated 5 juin 2023, 20:00:47 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;
import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * Modul generated by hbm2java
 */
@Entity
@Table(name = "modul", catalog = "pfe")
public class Modul implements java.io.Serializable {

	private Integer idModul;
	private Enseignant enseignant;
	private Filiere filiere;
	private String nomModul;
	private Set<Exercice> exercices = new HashSet<Exercice>(0);
	private Set<Chapitre> chapitres = new HashSet<Chapitre>(0);
	private Set<EtudianteModule> etudianteModules = new HashSet<EtudianteModule>(0);
	private Set<Quiz> quizs = new HashSet<Quiz>(0);

	public Modul() {
	}

	public Modul(Filiere filiere, String nomModul) {
		this.filiere = filiere;
		this.nomModul = nomModul;
	}

	public Modul(Enseignant enseignant, Filiere filiere, String nomModul, Set<Exercice> exercices,
			Set<Chapitre> chapitres, Set<EtudianteModule> etudianteModules, Set<Quiz> quizs) {
		this.enseignant = enseignant;
		this.filiere = filiere;
		this.nomModul = nomModul;
		this.exercices = exercices;
		this.chapitres = chapitres;
		this.etudianteModules = etudianteModules;
		this.quizs = quizs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_modul", unique = true, nullable = false)
	public Integer getIdModul() {
		return this.idModul;
	}

	public void setIdModul(Integer idModul) {
		this.idModul = idModul;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "enseignante", nullable = true)
	public Enseignant getEnseignant() {
		return this.enseignant;
	}

	public void setEnseignant(Enseignant enseignant) {
		this.enseignant = enseignant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "filier", nullable = false)
	public Filiere getFiliere() {
		return this.filiere;
	}

	public void setFiliere(Filiere filiere) {
		this.filiere = filiere;
	}

	@Column(name = "nom_modul", nullable = false, length = 45)
	public String getNomModul() {
		return this.nomModul;
	}

	public void setNomModul(String nomModul) {
		this.nomModul = nomModul;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modul")
	public Set<Exercice> getExercices() {
		return this.exercices;
	}

	public void setExercices(Set<Exercice> exercices) {
		this.exercices = exercices;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "modul")
	public Set<Chapitre> getChapitres() {
		return this.chapitres;
	}

	public void setChapitres(Set<Chapitre> chapitres) {
		this.chapitres = chapitres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modul")
	public Set<EtudianteModule> getEtudianteModules() {
		return this.etudianteModules;
	}

	public void setEtudianteModules(Set<EtudianteModule> etudianteModules) {
		this.etudianteModules = etudianteModules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modul")
	public Set<Quiz> getQuizs() {
		return this.quizs;
	}

	public void setQuizs(Set<Quiz> quizs) {
		this.quizs = quizs;
	}

}
