package com.example.demo.entity;
// Generated 5 juin 2023, 20:00:47 by Hibernate Tools 4.3.5.Final


import jakarta.persistence.*;

import static jakarta.persistence.GenerationType.IDENTITY;
/**
 * NoteQuiz generated by hbm2java
 */
@Entity
@Table(name = "note_quiz", catalog = "pfe")
public class NoteQuiz implements java.io.Serializable {

	private Integer idNote;
	private Etudiante etudiante;
	private Quiz quiz;
	private int noteQuiz;

	public NoteQuiz() {
	}

	public NoteQuiz(Etudiante etudiante, Quiz quiz, int noteQuiz) {
		this.etudiante = etudiante;
		this.quiz = quiz;
		this.noteQuiz = noteQuiz;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idNote", unique = true, nullable = false)
	public Integer getIdNote() {
		return this.idNote;
	}

	public void setIdNote(Integer idNote) {
		this.idNote = idNote;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEtu", nullable = false)
	public Etudiante getEtudiante() {
		return this.etudiante;
	}

	public void setEtudiante(Etudiante etudiante) {
		this.etudiante = etudiante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdQuiz", nullable = false)
	public Quiz getQuiz() {
		return this.quiz;
	}

	public void setQuiz(Quiz quiz) {
		this.quiz = quiz;
	}

	@Column(name = "note_quiz", nullable = false)
	public int getNoteQuiz() {
		return this.noteQuiz;
	}

	public void setNoteQuiz(int noteQuiz) {
		this.noteQuiz = noteQuiz;
	}

}
