package com.example.demo.entity;
// Generated 5 juin 2023, 20:00:47 by Hibernate Tools 4.3.5.Final

import jakarta.persistence.*;

import static jakarta.persistence.GenerationType.IDENTITY;
/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "pfe")
public class Question implements java.io.Serializable {

	private Integer idQst;
	private Quiz quiz;
	private String question;
	private String reponse;
	private Float note;

	public Question() {
	}

	public Question(Quiz quiz, String question) {
		this.quiz = quiz;
		this.question = question;
	}

	public Question(Quiz quiz, String question, String reponse, Float note) {
		this.quiz = quiz;
		this.question = question;
		this.reponse = reponse;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_qst", unique = true, nullable = false)
	public Integer getIdQst() {
		return this.idQst;
	}

	public void setIdQst(Integer idQst) {
		this.idQst = idQst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "quiz", nullable = false)
	public Quiz getQuiz() {
		return this.quiz;
	}

	public void setQuiz(Quiz quiz) {
		this.quiz = quiz;
	}

	@Column(name = "Question", nullable = false)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Column(name = "reponse")
	public String getReponse() {
		return this.reponse;
	}

	public void setReponse(String reponse) {
		this.reponse = reponse;
	}

	@Column(name = "note", precision = 12, scale = 0)
	public Float getNote() {
		return this.note;
	}

	public void setNote(Float note) {
		this.note = note;
	}

}
