package com.example.demo.entity;
// Generated 31 mai 2023, 18:41:19 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Quiz generated by hbm2java
 */
@Entity
@Table(name = "quiz", catalog = "pfe")
public class Quiz implements java.io.Serializable {

	private int idQz;
	private Modul module;
	private String titre;
	private Date dateAjoute;
	private Date dateLimite;
	private Set<Question> questions = new HashSet<Question>(0);

	public Quiz() {
	}

	public Quiz(int idQz, Modul module, String titre, Date dateAjoute, Date dateLimite) {
		this.idQz = idQz;
		this.module = module;
		this.titre = titre;
		this.dateAjoute = dateAjoute;
		this.dateLimite = dateLimite;
	}

	public Quiz(int idQz, Modul module, String titre, Date dateAjoute, Date dateLimite, Set<Question> questions) {
		this.idQz = idQz;
		this.module = module;
		this.titre = titre;
		this.dateAjoute = dateAjoute;
		this.dateLimite = dateLimite;
		this.questions = questions;
	}

	@Id

	@Column(name = "id_qz", unique = true, nullable = false)
	public int getIdQz() {
		return this.idQz;
	}

	public void setIdQz(int idQz) {
		this.idQz = idQz;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module", nullable = false)
	public Modul getModule() {
		return this.module;
	}

	public void setModule(Modul module) {
		this.module = module;
	}

	@Column(name = "titre", nullable = false, length = 45)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_ajoute", nullable = false, length = 10)
	public Date getDateAjoute() {
		return this.dateAjoute;
	}

	public void setDateAjoute(Date dateAjoute) {
		this.dateAjoute = dateAjoute;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date_limite", nullable = false, length = 10)
	public Date getDateLimite() {
		return this.dateLimite;
	}

	public void setDateLimite(Date dateLimite) {
		this.dateLimite = dateLimite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quiz")
	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

}
